# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orders',
            field=models.ManyToManyField(blank=True, to='socialapp.Order'),
        ),
    ]
