# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20160220_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
